doctrine:
    dbal:
        #        url: '%env(resolve:DATABASE_URL)%'
        #url: 'postgresql://challengesuser:challengespass@127.0.0.1:5432/challenges?serverVersion=16&charset=utf8'
        #url: 'postgresql://%env(resolve:POSTGRES_USER)%:%env(resolve:POSTGRES_PASSWORD)%@%env(resolve:POSTGRES_HOST)%:%env(resolve:POSTGRES_PORT)%/%env(resolve:POSTGRES_DB)%?serverVersion=15&charset=utf8'
        driver: pdo_pgsql
        dbname: '%env(POSTGRES_DB)%'
        host: '%env(POSTGRES_HOST)%'
        port: '%env(POSTGRES_PORT)%'
        user: '%env(POSTGRES_USER)%'
        password: '%env(POSTGRES_PASSWORD)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
