# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(CMS_ASSETS_PATH): '/'
    app.env: '%env(string:APP_ENV)%'
    app.server: '%env(string:APP_SERVER)%'
    app.route_prefix: '%env(CMS_PROJECT_ROUTE_PREFIX)%'
    public_uploads_dir: '%env(string:PUBLIC_UPLOADS_DIR)%'
    public_uploads_path: '%env(string:PUBLIC_UPLOADS_PATH)%'
    api_project_domain: '%env(string:API_PROJECT_DOMAIN)%'
    cms_project_domain: '%env(string:CMS_PROJECT_DOMAIN)%'
    cdn_enabled: '%env(bool:CDN_ENABLED)%'
    cdn_domain: '%env(string:CDN_DOMAIN)%'
    cms_project_dir: '%env(string:CMS_PROJECT_DIR)%'
    s3_bucket: '%env(string:AWS_S3_BUCKET)%'
    projectEmail: '%env(EMAIL)%'
    projectEmailName: '%env(EMAIL_NAME)%'
    webProjectDomain: '%env(WEB_PROJECT_DOMAIN)%'

framework:
    assets:
        #base_path: ''
        base_path: '/cms/public'
        enabled: true

services:
    # default configuration for services in *this* file
    _defaults:
        bind:
            $appEnv: '%app.env%'
            $appServer: '%app.server%'
            $webProjectDomain: '%webProjectDomain%'
            $cdnEnabled: '%cdn_enabled%'
            $cdnDomain: '%cdn_domain%'
            $apiDomain: '%api_project_domain%'
            $publicUploadsDir: '%public_uploads_dir%'
            $projectDir: '%kernel.project_dir%'
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Asset\EasyAdminAssetsPackage:
        decorates: EasyCorp\Bundle\EasyAdminBundle\Asset\AssetPackage
        arguments:
            $requestStack: '@request_stack'
            $basePath: '%env(CMS_ASSETS_PATH)%'

    App\Service\UserService:
        arguments:
            $publicUploadsDir: '%public_uploads_dir%'

    App\Service\Infrastructure\FFmpegService:
        arguments:
            $ffmpegBinariesPath: '%env(string:FFMPEG_BINARIES_PATH)%'
            $ffprobeBinariesPath: '%env(string:FFPROBE_BINARIES_PATH)%'

    App\Service\Infrastructure\RedisService:
        arguments:
            $redisIsEnable: '%env(bool:REDIS_IS_ENABLE)%'
            $redisQueueIsEnable: '%env(bool:REDIS_QUEUE_IS_ENABLE)%'

    App\Service\Infrastructure\S3Service:
        arguments:
            $s3Bucket: '%s3_bucket%'

    App\Service\Infrastructure\Mail\ProjectEmailAddressProvider:
        arguments:
            $email: '%projectEmail%'
            $name: '%projectEmailName%'

    App\Service\AuthService:
        arguments:
            $authPass: '%env(string:JWT_AUTH_PASS)%'

    Symfony\Component\Security\Http\Logout\LogoutUrlGenerator: '@security.logout_url_generator'

    Symfony\Component\Mailer\Bridge\Resend\Transport\ResendTransportFactory:
        tags:
            - { name: mailer.transport_factory }
